name: Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: central
        server-username: CENTRAL_USERNAME
        server-password: CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE

    - name: Build the dependencies of the api
      run: mvn -B install --file pom.xml -pl '!api'

    - name: Package
      working-directory: ./api
      run: mvn -B package --file pom.xml
      env:
        CENTRAL_USERNAME: SQIXE3CJ
        CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Upload SignGUI jar
      uses: actions/upload-artifact@v2
      with:
        name: SignGUI-Build
        path: api/target/signgui-2.3.2.jar